apiVersion: v1
kind: pod
metadata:
  name: node-selector-demo
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
  nodeSelector:
    disktype: ssd


  # kubectl label nodes <nodename> disktype=ssd