apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinfity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: hardware
                operator: In
                values:
                  - gpu
                  # preferredDuringSchedulingIgnoredDuringExecution:
                  #   - weight: 1
                  #     preference:
                  #       matchExpressions:
                  #         - key: another-node-label-key
                  #           operator: In
                  #           values:
                  #             - another-node-label-key
  containers:
    - name: with-node-affinfity
      image: nginx
